### ISSUE TITLE
Paginate with locals or data

### ISSUE THREAD

**Issue by lcpriest** [cantierecreativo/middleman-paginate#4]
Re: https://github.com/cantierecreativo/middleman-paginate/blob/master/lib/middleman/paginate/extension.rb#L42

I can't seem to get either of these to pass configuration through as frontmatter - any ideas?

**Comment by stefanoverna** [comment]
```ruby
paginate dato.articles, "/articles", "/templates/articles.html", per_page: 5, locals: { foo: "bar" }, data: { qux: "gee" }
```

Inside the `templates/articles.html.erb` you can reference them like this:

```erb
<%= foo %>
<%= current_page.data.qux %>
```

**Comment by lcpriest** [comment]
Odd! `data: {}` seems to work now.
