### ISSUE TITLE
Support for Pretty URLs (Directory Indexes)

### ISSUE THREAD

**Issue by robinlambert** [cantierecreativo/middleman-paginate#5]
It would be great if you could provide support for Pretty URLs (Directory Indexes).
At the moment, even if I enable directory indexes in my `config.rb`, the paginated pages urls will be displayed as `blog/page/2.html` instead of `blog/page/2`.

It would also be great if we could configure to have something else than `page/n`. For instance I would like to have `blog/2` instead of `blog/page/2`.

**Comment by stefanoverna** [comment]
Hi @robinlambert, I've released a new version of the gem to address the problem, this should generate pretty URLs now:

```ruby
paginate data.your_collection, "/episodes", "/templates/episodes.html", suffix: "/page/:num/index", per_page: 20
```
